openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0

paths:
  /api/users/:
    get:
      summary: Obtiene todos los usuarios previamente creados
      tags:
        - Users
      responses:
        "200":
          description: Los usuarios fueron obtenidos desde la base de datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    descripticon: Lista de usuarios
                  usuarios:
                    type: array
                    items:
                      $ref: '#components/schemas/User'
        "404":
          description: Usuarios no encontrados

    post:
      summary: Guarda un usuario
      tags:
        - Users
      responses:
        "201":
          description: Usuario creado
        "500":
          description: Error interno del servidor

  /api/users/{uid}:
    get:
      summary: Obtiene el usuario por número de id
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Número de id
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido del usuario
        email:
          type: string
          description: Correo electronico
        password:
          type: string
          description: Contraseña