openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0

paths:
  /api/users/{uid}:
    get:
      summary: Obtiene el usuario por número de id
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: El usuario fue obtenido desde la base de datos
        "404":
          description: Usuario no encontrado

    post:
      summary: Guarda un usuario
      tags:
        - Users
      responses:
        "201":
          description: Usuario creado
        "500":
          description: Error interno del servidor